# Generated by Django 5.0.6 on 2024-06-10 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_human_alter_story_options_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='game.human'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='game.story'),
        ),
    ]
