# Generated by Django 5.0.6 on 2024-06-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_chapter_human_alter_chapter_story'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('index', 'story'), ('story', 'human')},
        ),
    ]
