# Generated by Django 5.0.6 on 2024-06-14 20:07

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20240614_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='access_token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=128, unique=True),
        ),
    ]
